### ISSUE TITLE
Broken link to discourse forum

### ISSUE THREAD

**Issue by RossBoylan** [UIUC-PPL/charm4py#175]
https://charm4py.readthedocs.io/en/latest/contact.html has a link to a forum, which is https://charm.discourse.group/.
Clicking on it yields 
> unable to connect
>Firefox can’t establish a connection to the server at charm.discourse.group.

**Comment by matthiasdiener** [comment]
Thank you for pointing this out. We will switch to GitHub 'discussions'  as soon as that feature is available. For the time being, please use the issues for communication. 

Regarding the other two issues that you opened, we will get back to you as soon as possible (we are a bit short-staffed over the summer).
