### ISSUE TITLE
questions readonlies

### ISSUE THREAD

**Issue by jiazhenggod** [UIUC-PPL/charm4py#45]
is this the same as passing the variable into the constructor manually of the performance cost is smaller? I have a class which contains some method and list, and all of the method are only reading 
the data in the class. Those instances are very big. And I distributed them over 6 processors through 6 chares object. I tried readonlies but the performance does not have any improvement.Thanks

**Comment by juanjgalvez** [comment]
This is not an issue. For the future, could you please post questions to the forum (https://charm.discourse.group/c/charm4py) instead? Thanks

Regarding your question, there shouldn't be any performance difference between the two approaches. The main difference is that readonlies serves to conveniently place data that you want to broadcast to every process inside a container which can easily be accessed by *any* chares on the process. So, different chares (of potentially different types) in the same process can share the data.
