### ISSUE TITLE
printStats does not reflect all timings (mostly timings inside charm++ library)

### ISSUE THREAD

**Issue by Jiazheng-Yuan** [UIUC-PPL/charm4py#46]
<img width="455" alt="2018-12-12 8 01 19" src="https://user-images.githubusercontent.com/25042587/49910559-c02bda80-fe48-11e8-8c52-8a6be7d630d1.png">

I used  the charms.printStat() , and this is the provided info. However, I also did a timing, which is right in front the creation of any chares object and right after I get all the results from the future. Nothing is in between Timing result obtained this way shows an extra ten second. doess printStat() hide any part of calculation? Thanks

**Comment by juanjgalvez** [comment]
There have been several improvements in profiling to give more accurate timings, although some limitations of the profiler still stand. The documentation now explains this more clearly, please refer to that:
https://charm4py.readthedocs.io/en/latest/profiling.html
